spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 2024indorV1
        url: jdbc:mysql://localhost:3306/indor_callejero
        username: root
        jpa:
            hibernate:
                ddl-auto: create-drop
            show-sql: true
        logging:
            level:
                org.hibernate.SQL: DEBUG
                org.hibernate.type.descriptor.sql.BasicBinder: TRACE